### ISSUE TITLE
New message after patch

### ISSUE THREAD

**Issue by Harlock1978** [WessellUrdata/vbmeta-disable-verification#1]
I installed my OS with a blank vbmeta for boot.img and I get a bootloop, after patching the original vbmeta with your script I don't have any bootloop anymore even with a modded boot.img, but now I have this message:

Orange State
OS not verified or Custom OS. Press a button within 5 seconds to continue.

Should I patch an empty vbmeta?

**Comment by WessellUrdata** [comment]
Sorry for the late reply, and thanks for your interest in this repo.

I don't think you're supposed to use an empty vbmeta. I'm not familiar with Android Custom ROM stuff anymore, but a quick search yielded this thread on XDA and especially [this reply](https://xdaforums.com/t/closed-what-is-vbmeta-img.3931588/post-81790693) which is probably what you need to know.

Orange State just means your phone has an unlocked bootloader, which should be expected. [Read More at Google's Android Verified Boot 2.0 README](https://android.googlesource.com/platform/external/avb/+/1614f552a53d9dcd85ff404156422d935ebdb1a4/README.md#Android-Specific-Integration)

**Comment by Harlock1978** [comment]
Thank you for your answer, I used an empty Vbmeta because it works well with android 10 and 12, my two previous Ulefone handy and it work fine with the UE version of the ROM of my actually phone together with 

`fastboot flash --disable-verity --disable-verification vbmeta vbmeta.img`

but it doesn't work with the Not UE ROM where I had a bootloop with a message claiming that the phone cannot be trust.
I was able to enter fastboot mode in the phone, but than it was not recognised by the pc, so I had to flash the orginial vbmeta patched with you script and now I had a different message, but without bootloop.

Thanks for the links, I will study them
